# Generated by Django 6.0.5 on 2026-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_instructorprofile_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='staff_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
