# Generated by Django 6.0.5 on 2026-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_enrollment_status_alter_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
