# Generated by Django 6.0.5 on 2026-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_submission_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
    ]
