# Generated by Django 6.0.5 on 2026-06-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_materials_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='materials',
            name='file_name',
            field=models.TextField(default=''),
        ),
    ]
