# Generated by Django 6.0.5 on 2026-06-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_file_submission_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file_url',
        ),
    ]
