# Generated by Django 6.0.5 on 2026-06-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_assignment_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='file_type',
            field=models.CharField(max_length=100),
        ),
    ]
