# Generated by Django 6.0.5 on 2026-05-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='creatd_at',
            new_name='created_at',
        ),
    ]
