# Generated by Django 6.0.5 on 2026-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_instructorprofile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_graded',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded')], default='submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
