# Generated by Django 6.0.5 on 2026-06-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_submission_is_graded_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
